### ISSUE TITLE
Буква Ё в заголовке главы + странности с текстом

### ISSUE THREAD

**Issue by korn3r** [abalabokhin/iwd2_rus#1]
Здравствуйте.
Играю с вашим переводом и заметил две странности.
1. Заглавная буква Ё почему-то отсутствует в заголовках (как-минимум в названии четвертой главы) https://imgur.com/a/Xc7ifA7
2. Одни и те же диалоги порой то на русском, то на английском, в зависимости от того какой персонаж общается с нпц. С Вейрой такая проблема точно замечена. Уже не помню с каким нпц общался, но было так что если основным чаром общаюсь, то русский, если Вейрой говорю, то на английском.
3. Ну и в целом часто натыкаюсь на отдельные диалоговые опции, которые на английском (например 3-4 варианта ответа на русском, 1 на английском). Но это видимо надо просто участвовать в переводе, а не создавать баг. 

Версия игры 2.01 (101616) GOG + Enchanced Edition (последний на данный момент)

Пункты 2 и 3 конечно довольно размыто звучат (извините, скриншотов не додумался наделать), но хотя бы со шрифтом есть скрин.
И если где-то можно поучаствовать в допереводе контента из EE, скажите пожалуйста, на досуге поучаствую.

**Comment by abalabokhin** [comment]
За букву Ё спасибо, попробуем исправить. А вы установили последнюю версию мода (IWD2EE) на русском языке из репозитория? Там должно быть уже все переведено. 
Выглядит пока, что перевод iwd2 установлен правильно на русском, а IWD2EE установлен на английском почему-то. Выложите ваш Weidu.log, пожалуйста.

**Comment by korn3r** [comment]
Ставил последнюю версию перевода на тот момент (14 марта, судя по логу 2.3)
на самую свежую версию EE (3.2.9 от февраля)
Половина спеллов и вещей на английском. Многие диалоги тоже.

Если это важно, ставил сначала EE, потом русификатор.

**Comment by korn3r** [comment]
> За букву Ё спасибо, попробуем исправить. А вы установили последнюю версию мода (IWD2EE) на русском языке из репозитория? Там должно быть уже все переведено. Выглядит пока, что перевод iwd2 установлен правильно на русском, а IWD2EE установлен на английском почему-то. Выложите ваш Weidu.log, пожалуйста.

По почте лог не прикрепился похоже.

[WeiDU.log](https://github.com/abalabokhin/iwd2_rus/files/14696487/WeiDU.log)

**Comment by abalabokhin** [comment]
А ну так в IWD2EE официальном нет русского языка еще, конечно у вас все строчки, которые добавлялись или менялись в IWD2EE будут на английском. Мы не так давно перевели IWD2EE, но еще не послали перевод авторам. Тем не менее перевод можно уже поставить и играть, вот из этого репозитория: https://github.com/abalabokhin/IWD2EE (это полная копия последней версии официального репозитория + русский перевод). Ставьте по инструкции из первого поста отсюда: (https://arcanecoast.ru/forum/viewtopic.php?t=1859) - там важно соблюсти очередность, чтобы все строки в конечном счете оказались правильными.

**Comment by korn3r** [comment]
> А ну так в IWD2EE официальном нет русского языка еще, конечно у вас все строчки, которые добавлялись или менялись в IWD2EE будут на английском. Мы не так давно перевели IWD2EE, но еще не послали перевод авторам. Тем не менее перевод можно уже поставить и играть, вот из этого репозитория: https://github.com/abalabokhin/IWD2EE (это полная копия последней версии официального репозитория + русский перевод). Ставьте по инструкции из первого поста отсюда: (https://arcanecoast.ru/forum/viewtopic.php?t=1859) - там важно соблюсти очередность, чтобы все строки в конечном счете оказались правильными.

А, извините. Что-то не допер что они отдельные.
Ну, тогда щас поставлю. Надеюсь не окажется что багованные виверны\Вейра это потому что я еще и не тот ЕЕ поставил.

**Comment by abalabokhin** [comment]
Про багованых виверн я ничего не знаю, но версия в этом репозитории целиком совпадает с версией IWD2EE Version 3.2.9 за исключением русского перевода. Напишите по результатам, как получится все установить, нам нужен фидбек и бетатестры перевода :) . Issue пока не закрываю - она будет висеть открытой и ждать вашего комментария, да и буква Ё еще не поправлена...

**Comment by korn3r** [comment]
> Про багованых виверн я ничего не знаю, но версия в этом репозитории целиком совпадает с версией IWD2EE Version 3.2.9 за исключением русского перевода. Напишите по результатам, как получится все установить, нам нужен фидбек и бетатестры перевода :) . Issue пока не закрываю - она будет висеть открытой и ждать вашего комментария, да и буква Ё еще не поправлена...

Скачал, установил (запустил заново новый Setup-iwd2ee.exe), но многие описания и названия вещей все равно на английском. Причем вроде как оригинальные. Например скроллы Animate Skeleton, Haste, Animate Zombie, Reanimate и другие.
Некоторые диалоги тоже (Например диалог с Нонином в Raven Monastery, если с ним говорит Вейра, если созданным персонажем, то все на русском).

Это может быть связано с тем что после установки русификатора нужно начинать игру заново? Бетатестером я рад бы побыть, но если с 4го акта придется заново начинать, то уже не так сильно готов...

**Comment by abalabokhin** [comment]
Насколько я знаю, не должно быть английского ничего (даже для старых сейвов), если вы все правильно установили... Попробуйте еще открыть ваш dialog.tlk (файл бинарный, но по идее его можно открыть в каком-нибудь notepad++ в кодировке cp1251) - и поискать ближе к концу - там не должно быть английских строчек совсем. Так же можно переустановить IWD2EE предварительно удалив папку tra/English - тогда английским текстам будет просто неоткуда взяться. Ну и переставляйте на чистую iwd2 - вроде бы iwd2ee както некорректно себя удаляет. Кроме вышеперечисленного других идей пока нет.

**Comment by korn3r** [comment]
> Насколько я знаю, не должно быть английского ничего (даже для старых сейвов), если вы все правильно установили... Попробуйте еще открыть ваш dialog.tlk (файл бинарный, но по идее его можно открыть в каком-нибудь notepad++ в кодировке cp1251) - и поискать ближе к концу - там не должно быть английских строчек совсем. Так же можно переустановить IWD2EE предварительно удалив папку tra/English - тогда английским текстам будет просто неоткуда взяться. Ну и переставляйте на чистую iwd2 - вроде бы iwd2ee както некорректно себя удаляет. Кроме вышеперечисленного других идей пока нет.

У меня dialog.tlk наполовину английский, наполовину русский. Создал новую пати (соло Сорк) - начало игры на русском. Создал еще одну - все (самый первый диалог с Хедроном) на английском. 

В общем попробую с нуля. Спасибо.

**Comment by korn3r** [comment]
> Насколько я знаю, не должно быть английского ничего (даже для старых сейвов), если вы все правильно установили... Попробуйте еще открыть ваш dialog.tlk (файл бинарный, но по идее его можно открыть в каком-нибудь notepad++ в кодировке cp1251) - и поискать ближе к концу - там не должно быть английских строчек совсем. Так же можно переустановить IWD2EE предварительно удалив папку tra/English - тогда английским текстам будет просто неоткуда взяться. Ну и переставляйте на чистую iwd2 - вроде бы iwd2ee както некорректно себя удаляет. Кроме вышеперечисленного других идей пока нет.

Я дико извиняюсь, НО:
Поставил все с нуля (оказалось надо было русификатор ДО Enchanced Edition ставить, да). Скроллы, описания классов, параметров и примерно все что я вижу стало на русском. НО - когда Вейра (призрак из Таргоса, которого можно взять в пати) говорит с НПЦ, диалоги все равно на английском. Причем именно Вейра, если говорить другим чаром (созданным), то ровно те же самые диалоги на русском.
В dialog.tlk при этом английского нет.

UPDATE:
Починил... переименовал файл dialog**f**.tlk в 1dialog**f**111.tlk (кто его знает по какой оно там маске его читает) и теперь диалоги с Вейрой тоже на русском.
Это очень большая проблема если игра этот файл (dialog**F**.tlk) не находит?

**Comment by korn3r** [comment]
И еще забавный косяк получился (возможно из-за того что патчил заново игру и подпихивал сейв) - вначале игры в таргосе у оружейного вендора  увидел меч с названием "Сердце героя: Cleric" (я назвал первого персонажа в пати "Cleric"), купил его и всю игру с ним бегал... на нем же буквально написано имя моего персонажа :) (да и +1 ко всем статам норм бонус). После перестановки русификации меч теперь называется "Сердце героя: Вейра"....
В целом ладно, просто странно что он решил переименоваться

**Comment by abalabokhin** [comment]
> Поставил все с нуля (оказалось надо было русификатор ДО Enchanced Edition ставить, да). Скроллы, описания классов, параметров и примерно все что я вижу стало на русском. НО - когда Вейра (призрак из Таргоса, которого можно взять в пати) говорит с НПЦ, диалоги все равно на английском. Причем именно Вейра, если говорить другим чаром (созданным), то ровно те же самые диалоги на русском. В dialog.tlk при этом английского нет.
> 
> UPDATE: Починил... переименовал файл dialog**f**.tlk в 1dialog**f**111.tlk (кто его знает по какой оно там маске его читает) и теперь диалоги с Вейрой тоже на русском. Это очень большая проблема если игра этот файл (dialog**F**.tlk) не находит?

Ура. Ну да ставить нужно было по инструкции - там этот порядок правильно указан, я же не зря инструкцию писал :) . Файл dialogf.tlk нужен для реплик для женского персонажа. То есть начинаешь разговор за женского персонажа, все реплики берутся из файла dialogf.tlk. Судя по всему во время экспериментов что-то произошло и этот файл оказался с английской версией. Я еще потестирую этот момент - по идее при наличие этого файла - туда должна правильно накатываться выбранная локализация (русская или английская). 

Но вообще вам этот файл не нужен - все реплики в переводе делались гендерно-нейтральными. Так что да просто переименуйте его или удалите и тогда все реплики будут браться из dialog.tlk и все должно работать хорошо.

Почему меч оказался с другим именем, не знаю, но это баг из-за старого сейва и всегда рекомендация одна - начать все заново ).

**Comment by abalabokhin** [comment]
А еще у вас не осталось сейвов перед 4 главой? У вас получится взять файл из архива ([stonebig.bam.zip](https://github.com/abalabokhin/iwd2_rus/files/14705076/stonebig.bam.zip)), скопировать его с заменой в папку override в корне игры и посмотреть починилась ли буква Ё в надписи ЧЕТВЁРТАЯ ГЛАВА. А то очень долго до туда проходить. Спасибо, если получится.

**Comment by korn3r** [comment]
> А еще у вас не осталось сейвов перед 4 главой? У вас получится взять файл из архива ([stonebig.bam.zip](https://github.com/abalabokhin/iwd2_rus/files/14705076/stonebig.bam.zip)), скопировать его с заменой в папку override в корне игры и посмотреть починилась ли буква Ё в надписи ЧЕТВЁРТАЯ ГЛАВА. А то очень долго до туда проходить. Спасибо, если получится.

Спасибо, теперь вроде норм. https://imgur.com/a/qtkZ5GY

_"Ну да ставить нужно было по инструкции - там этот порядок правильно указан, я же не зря инструкцию писал :)"_
Это да, но я качал с гитхаба и инструкции по установке тут не нашел. Где она на гитхабе запрятана то?


Ну и еще минибаг: В меню персонажа в спеллах в правом верхнем углу написано "Уровень заклинаний" в две строчки и слово заклинания даже не влазит в экран. Может там просто слово "Уровень" оставить?
https://imgur.com/a/Vfsg0BQ

**Comment by abalabokhin** [comment]
Тут нет инструкции (точно не в этом моде, это мод перевода оригинальной игры). Но я же вам давал ссылку вот тут:
> Ставьте по инструкции из первого поста отсюда: (https://arcanecoast.ru/forum/viewtopic.php?t=1859) - там важно соблюсти очередность, чтобы все строки в конечном счете оказались правильными.

Спасибо за тест с буквой ё, добавлю тогда этот шрифт в мод. И поправил "Уровень", за это тоже спасибо. Вообще, если найдёте еще косяки, где что-то куда-то не влазит - пишите - я переводил элементы интерфейса вслепую - так что так может такое еще быть.

**Comment by korn3r** [comment]
> Тут нет инструкции (точно не в этом моде, это мод перевода оригинальной игры). Но я же вам давал ссылку вот тут:
> 
> > Ставьте по инструкции из первого поста отсюда: (https://arcanecoast.ru/forum/viewtopic.php?t=1859) - там важно соблюсти очередность, чтобы все строки в конечном счете оказались правильными.
> 
> Спасибо за тест с буквой ё, добавлю тогда этот шрифт в мод. И поправил "Уровень", за это тоже спасибо. Вообще, если найдёте еще косяки, где что-то куда-то не влазит - пишите - я переводил элементы интерфейса вслепую - так что так может такое еще быть.

Про инструкцию это я уже туплю... Сложно в общем русификатор пока на ЕЕ ставится, как я понял. Но пока вроде работает. Спасибо.
А файл, отвечающий за "Уровень" можно тоже скачать где-то?  Второй раз в жизни играю (первый раз лет 20 назад пробовал), что-то ломают лицо моей пати из 4х чаров (особенно эти глючащие виверны, которые видимо вопрос к самому ЕЕ), и приходится постоянно лазить спеллы переставлять, и как-то глаза мозолит :)

А так если что найду, напишу.

**Comment by abalabokhin** [comment]
Это строчка в переводе оригинальной игры (надеюсь я ее правильно нашел) - придется еще раз все переставить (вначале перевод оригинальной игры, потом IWD2EE), если вы готовы так заморачиватся, то берите свежий перевод игры (https://github.com/abalabokhin/iwd2_rus/archive/refs/heads/main.zip) и вперед.

**Comment by abalabokhin** [comment]
Сейчас подумал, в целом есть вариант разбить текущий tlk файл на реплики, найти там нужную, попрпавить и собрать обратно. Это придется немного поколдовать с weidu, но ничего неподъемного. Это может быть проще, чем переставлять все заново, вот тут написано как: https://arcanecoast.ru/publication/Kak_nastroit%27_imena_i_nazvaniya_v_igre_na_svoj_vkus
Вам надо будет найти в полученном tra файле строчку "Уровень заклинания" и исправить на "Уровень"...

**Comment by abalabokhin** [comment]
И да, issue я закрываю, если будут еще какие-то баги - открывайте новые.
