### ISSUE TITLE
Буква М в описании Шлема защиты от чар.

### ISSUE THREAD

**Issue by korn3r** [abalabokhin/iwd2_rus#2]
И снова я выхожу на связь... (от создателей тикета "[буква Ё в заголовке главы](https://github.com/abalabokhin/iwd2_rus/issues/1)")
В описании шлема "Шлем защиты от чар" пропущена буква М в "_владелец шлема обладает иммунитетом к любым форма очарования или господства_".
https://imgur.com/a/TImtdDW

Прощу прощения что создаю тикет про одну единственную опечатку, просто не уверен что найду еще.
Ну и это ЕЕ, в прошлом тикете мне уже указали что это перевод оригинала, но 1) я не очень понимаю куда слать баги по ЕЕ переводу 2) шлем скорее всего из оригинальной игры все равно...

**Comment by abalabokhin** [comment]
Благодарю, я поправил - это строчка как раз из EE (шлем был в оригинале, но описание для ЕЕ было изменено), давайте тогда оставим эту Issue открытой, пишите все опечатки, какие найдёте, сюда.

**Comment by korn3r** [comment]
Не совсем опечатка...
https://imgur.com/a/XMG8vz4

В диалоге с Ойнчак'Ольп на его вопрос "Мой камень у тебя?" есть два одинаковых ответа "Нет, я еще нет".
При том что помимо того что два одинаковых пункта, сам ответ не совсем подходит. Возможно в оригинале вопрос был "Ты уже нашел мой камень?"
При этом если выбрать нижний вариант "нет, я еще нет", то нпц отвечает "Найди мне его....", а если верхний, то нпц говорит что "Ложь, отдай его мне" (камень уже у меня в сумке на момент диалога) и далее два варианта - отдать и сказать что хочу оставить у себя.
Имхо нижний (вариант 3 на скриншоте) в таком случае должен быть просто "Нет, еще нет", а верхний (вариант 2) "Эм...нет...".  Ну или пунта 3 не должно быть в диалоге, если камень в сумке - не знаю как правильней.
update: напутал с вариантами в пункте про "имхо". исправил.

**Comment by abalabokhin** [comment]
Ну саму кривую реплику я исправил (на "нет, ещё нет") - но проблема в том, что она одна такая... Судя по всему как-то не так диалог прописан, что там реплика дублируется - такого не должно быть. Должна одна и та же реплика вести к разным вариантам ответа в зависимости от того, есть в наличии камень или нет.

Подозреваю, что IWD2EE менял чтото в этом диалоге и появился этот косяк. По возможности делайте сейвы для таких случаев - потом можно будет установить английскую версию мода, загрузить сейвы, понаделать скриншотов и послать авторам мода - пусть исправляют.

Да, конечно, нескладушки в диалогах тоже присылайте - будет возможность - поправим.

**Comment by korn3r** [comment]
Вот еще:
https://imgur.com/a/iyKlJGO

Сверху "Выбор заклинаний волшебника: Уровень 9" не влазит в экран.
Предлагаю "Уровень X : Волшебник"

Справа надпись "Можно выбрать 2 заклинан(ий/ие) для книги заклинаний"
Во-первых ий/ие как-то некрасиво в принципе, во-вторых подходящего окончания там и нет все равно.
Предлагаю "Можно добавить заклинания в книгу заклинаний: X шт." (я полагаю число же там просто тегом посреди текста)

Справа снизу текст на кнопке "Сбросить заклинания" тоже не помещается. Можно наверное просто "Сбросить".


Про багованный диалог создал тикет в issues у самого ЕЕ. https://github.com/RedChimera/IWD2EE/issues/113

**Comment by korn3r** [comment]
И еще по гую:
https://imgur.com/a/DtiCYsP

Справа снизу текст "Повышение уровня" прям вообще в кнопку не влезает. Предлагаю "Новый уровень"
Кнопка "Изменить группу" тоже не совсем помещается + не совсем отражает то что эта кнопка делает. Предлагаю "Исключить" (т.к. эта кнопка исключает из группы)

плюс опечатка в описании меча "Конец копейщика"
https://imgur.com/a/Icyxv7E

**Comment by abalabokhin** [comment]
Благодарю - прямо отличный фидбек, спасибо! Продолжайте в том же духе! Всё поправил (иногда использовал ваш вариант, иногда свой), кроме "Изменить группу" - она вроде нормально выглядит и на английском это именно "Reform Party". Изменения сразу не попадают в версию, пригодную для установки - так что если вы решите переустановить мод с изменёнными строчками - дайте мне знать, я подготовлю его для этого.

**Comment by korn3r** [comment]
Про Reform Party мне и на английском не понятно почему так. Кнопка просто исключает персонажа из группы, так что по-моему логичнее "Исключить", тем более "Исключить" точно влезет в кнопку нормально (там на самой кнопке еще рамка под текст нарисована, и в нее сейчас на русском не совсем помещается) :)

**Comment by abalabokhin** [comment]
Я на всякий случай уточню (так как сам не играл) - то есть эта кнопка просто убирает текущего персонажа из группы? В Baldur's Gate 1/2 такая кнопка, например, вызывает отдельное меню, где уже можно выбрать какого персонажа убрать из группы и нажать на дополнительную кнопку "Remove". Если тут происходит удаление сразу (без дополнительного меню) - тогда можно сделать "Исключить", да.

**Comment by korn3r** [comment]
> Я на всякий случай уточню (так как сам не играл) - то есть эта кнопка просто убирает текущего персонажа из группы? В Baldur's Gate 1/2 такая кнопка, например, вызывает отдельное меню, где уже можно выбрать какого персонажа убрать из группы и нажать на дополнительную кнопку "Remove". Если тут происходит удаление сразу (без дополнительного меню) - тогда можно сделать "Исключить", да.

Да, просто исключает. Я ее когда увидел, из названия не понял что она делает и нажал - чар сразу (без доп меню или подтверждений) исключается из группы и все. Остается на том месте где был исключен уже вне группы.

**Comment by korn3r** [comment]
> Благодарю - прямо отличный фидбек, спасибо! Продолжайте в том же духе! Всё поправил (иногда использовал ваш вариант, иногда свой), кроме "Изменить группу" - она вроде нормально выглядит и на английском это именно "Reform Party". Изменения сразу не попадают в версию, пригодную для установки - так что если вы решите переустановить мод с изменёнными строчками - дайте мне знать, я подготовлю его для этого.

Подскажите пожалуйста, а новые исправления по этой же ссылке качать? Я бы просто проверил, но у меня установка мода под два часа на древнем ноуте идет :)
https://github.com/abalabokhin/iwd2_rus/archive/refs/heads/main.zip

**Comment by korn3r** [comment]
Еще:
https://imgur.com/a/FGVwP0v

Лог боя, вторая строчка.
"Лучник юан-ти не подвергается действию моего огонь урона"
Предлагаю по возможности сделать конструкцию "Монстр не подвергается действию моего урона: тип урона"

**Comment by abalabokhin** [comment]
Так все поправил (включая "Исключить"). Иногда, я не уверен, что правлю правильные вещи, так что какие-то ошибки могут повторяться или изменятся, не бойтесь писать о них снова. Качать все по той же ссылке (большинство правок в iwd2ee моде, но есть и парочка в моде перевода основной игры, его можно качать по ссылке - https://github.com/abalabokhin/iwd2_rus/archive/refs/heads/main.zip).

**Comment by korn3r** [comment]
> Так все поправил (включая "Исключить"). Иногда, я не уверен, что правлю правильные вещи, так что какие-то ошибки могут повторяться или изменятся, не бойтесь писать о них снова. Качать все по той же ссылке (большинство правок в iwd2ee моде, но есть и парочка в моде перевода основной игры, его можно качать по ссылке - https://github.com/abalabokhin/iwd2_rus/archive/refs/heads/main.zip).

Кстати. Этот установщик (русификатора) в логе установки не упоминает dialogf.tlk совсем. И он (dialogf.tlk) чисто английский, без единого русского слова.

При этом дата последнего изменения у dialogf.tlk та же что и у обычного....хотел я написать, а потом проверил что у моего дистра оригинальной игры (скопированная папка) вообще нет dialogf.tlk, получается русификатор создает его сам, причем английским... Странно.
```
Choose your language:
 0 [English]
 1 [Russian]
1
Using Language [Russian]

Install Component [Icewind Dale 2 Translator]?
[I]nstall, or [N]ot Install or [Q]uit? i

Installing [Icewind Dale 2 Translator] [V2.3]
Copying 1 file ...
Copying 1 file ...
Copying 1 file ...
Copying 1 file ...


[./dialog.tlk] created, 41422 string entries

SUCCESSFULLY INSTALLED      Icewind Dale 2 Translator

Press ENTER to exit.
```

**Comment by korn3r** [comment]
> При этом дата последнего изменения у dialogf.tlk та же что и у обычного....хотел я написать, а потом проверил что у моего дистра оригинальной игры (скопированная папка) вообще нет dialogf.tlk, получается русификатор создает его сам, причем английским... Странно.


Ха... запустил русификатор еще раз (уже после того как dialogf.tlk создался), и получил:
```
...
[.\dialog.tlk] created, 41422 string entries
[.\dialogf.tlk] created, 41422 string entries
...
```
Получается при отсутствии файла dialogf.tlk, установщик его создает, но не переводит...

**Comment by korn3r** [comment]
> Так все поправил (включая "Исключить"). Иногда, я не уверен, что правлю правильные вещи, так что какие-то ошибки могут повторяться или изменятся, не бойтесь писать о них снова. Качать все по той же ссылке (большинство правок в iwd2ee моде, но есть и парочка в моде перевода основной игры, его можно качать по ссылке - https://github.com/abalabokhin/iwd2_rus/archive/refs/heads/main.zip).

По поводу **окна выбора новых заклинаний**:
https://imgur.com/a/rizdevW

1. Немного смущает слово "Можно" в "Можно выбрать новых заклинаний". Сразу вспоминается что в армии говорили про "Можно..." :)
Не очень большая проблема, но все таки окно огромное и можно поразвёрнутей написать, например "Выберите новые заклинания для записи в книгу заклинаний персонажа - X шт". Ну или хотя бы "Доступен выбор новых заклинаний: Х шт"

2. Вместо "Выбор заклинаний: 9 уровень" я бы написал "Класс - Уровень Х". Про то что это "выбор заклинаний" и без того написано в окне справа, а вот класс нигде не указан. Это не то чтобы суперпроблема, т.к. игрок скорее всего помнит какой класс он только что выбрал для прокачивания, но все равно лучше когда важная информация присутствует на таком довольно важном окне. В теории с мультиклассом можно ткнуть прокачать какой-то один из классов, отойти от компа на этом окне, а потом не вспомнить какой из классов прокачивал :) Очень условно-гипотетическая проблема, но все равно проще иметь класс на экране. Тем более что с этого окна нельзя вернуться назад.
К тому же изначально класс там был. 




**"Быстрые предметы"** тоже не помещается на экране.
https://imgur.com/a/D6Zrpu5
Предлагаю "Быстрый доступ".
Еще на самой панели при редактировании панели позиция называется "быстрый предмет".
Можно либо там тоже поменять на "Быстрый доступ", либо в инвентаре сделать в единственном числе ("Быстрый предмет") - там как раз "Ы" не влазит.
Имхо Быстрый доступ как-то красивее, чем единственное число у трех предметов.



**Описание мешочка самоцветов**:
https://imgur.com/a/vKshbef

"... в него помещается вплоть до двадцати подобных предметов"
Звучит довольно странно... Т.к. позиций у меня в этом мешочке уже 42. При этом самоцветы там хранятся действительно стопками по 20штук, но они стопками по 20шт и в инвентаре хранятся... В общем довольно странное описание, из которого я изначально сделал вывод что это мешочек на 20 слотов, а оказалось нет.

То же самое с "Сумка для зелий" и "Футляр для свитков" - написано "...вплоть до двадцати зелий/магических свитков", а у меня их там штук по 30 слотов занято.


**Описание "Сапоги скорости".**
"Особенности: скорость перемещения увеличенная вдвое" - правильнее наверное "скорость перемещения увеличивается вдвое" или "скорость перемещения удваивается"

**Comment by abalabokhin** [comment]
Так, с установщиком iwd2_rus я разобрался - нельзя копировать dialog.tlk файл во время установки мода - он там уже подгружен в память и его, судя по всему, никак не выгрузить. В общем я убрал автоматическое создание dialogf.tlk, его нужно или копировать руками или я добавил батник, для тех, кому лень. Но если ставить только iwd_rus  и iwd2ee - женский файл не нужен - и он автоматически не будет создаваться. В общем, теперь при установке двух этих модов на голую iwd2 - дожно быть все хорошо.

> 1. Немного смущает слово "Можно" в "Можно выбрать новых заклинаний". Сразу вспоминается что в армии говорили про "Можно..." :)
>        Не очень большая проблема, но все таки окно огромное и можно поразвёрнутей написать, например "Выберите новые заклинания для записи в книгу заклинаний персонажа - X шт". Ну или хотя бы "Доступен выбор новых заклинаний: Х шт"

Я не служил в армии и у меня нет плохих ассоциаций на это слово, а также я не считаю, что нужно увеличивать текст специально, чттобы он вмещался в большие окна. В общем, я подумаю над другими вариантами, но пока оставлю, как есть - коротко и понятно.

> 2\. Вместо "Выбор заклинаний: 9 уровень" я бы написал "Класс - Уровень Х". Про то что это "выбор заклинаний" и без того написано в окне справа, а вот класс нигде не указан. Это не то чтобы суперпроблема, т.к. игрок скорее всего помнит какой класс он только что выбрал для прокачивания, но все равно лучше когда важная информация присутствует на таком довольно важном окне. В теории с мультиклассом можно ткнуть прокачать какой-то один из классов, отойти от компа на этом окне, а потом не вспомнить какой из классов прокачивал :) Очень условно-гипотетическая проблема, но все равно проще иметь класс на экране. Тем более что с этого окна нельзя вернуться назад.
>         К тому же изначально класс там был.

 Там был не класс, там было "select arcane spell", в игре есть divine spell (друиды, священники, палы, следопыты), и arcane spell (колдуны, маги, барды). И речь идет про арканные заклинания. Но в переводах игры и мода везде используются "заклинания волшебника" и нет слова "арканные" - и здесь мы конечно не будет вводить непонятный и новый термин. А слова "волшебника или волшебные или магические" - очень длинные и без сокращения не влезут все равно... Да и выбирать при новом уровне можно только "арканные" заклинания - divine заклинания даются автоматически. В общем я решил убрать это смущающее слово "арканные" - ибо оно не несет никакого смысла.

Про все остальное позже напишу.

**Comment by korn3r** [comment]
_"А слова "волшебника или волшебные или магические" - очень длинные и без сокращения не влезут все равно"_
"Волшебство - Уровень Х" бы влезло, да и в перках есть "Знание (Волшебство)". Но в целом если выбираются только они, то наверное норм. Я что-то не подумал что "заклинания волшебника" не привязаны к классу волшебника :)

**Comment by abalabokhin** [comment]
Так я исправил "быстрые предметы" на "быстрый доступ" в том одном месте, но трогать "быстрый предмет" не стал - там несколько таких строчек и я побоялся чтонить еще сломать. Пусть будет слегка по разному - вроде понятно о чем идёт речь. К тому же там есть еще и "быстрое заклинание" и еще чтото похожее, и делать "быстрый доступ" - можно решить, что это быстрый доступ ко всему, а тут только к предметам.

Про мешочки не помогу - это используется оригинальное описание (эти строки не меняются в iwd2ee) и оно по английски звучит "It can hold up to twenty of such items." Возможно в iwd2ee изменили предмет, а описание забыли изменить или даже в оригинальном iwd2 описание было неверное. В любом случае, я бы написал об этом баге авторам iwd2ee, пусть они думают, что с этим делать - или менять описание под предмет или предмет под описание.

Сапоги скорости поправил. Вроде все на данный момент. 

PS Напоминаю, что недостаточно просто взять последние версии мода - надо еще мне об этом сказать, чтобы я их подготовил (мне нужно будет перекодировать файлы и мне лень делать это каждый раз, потому если не планируется переставлять моды - я бы предпочел все поправить, а уже потом все перекодировать). Но если хочется получить все свежие правки - тогда перекодирую, конечно.

**Comment by korn3r** [comment]
Спасибо. Пока не горит все правки получить, подожду.

**Comment by korn3r** [comment]
По поводу _"Там был не класс, там было "select arcane spell", в игре есть divine spell (друиды, священники, палы, следопыты), и arcane spell (колдуны, маги, барды). И речь идет про арканные заклинания. Но в переводах игры и мода везде используются "заклинания волшебника" и нет слова "арканные" - и здесь мы конечно не будет вводить непонятный и новый термин."_

Сейчас на игре со старой версией русификатора выбрал своему волшебнику мультиклассом Колдуна (очень нужно было пенальти на опыт получить), и при выборе заклинаний написано "Выбор заклинания мага..." вместо "Выбор заклинаний волшебника...", как было написано когда я волшебника прокачивал. Да и описание в правом окне другое.
Вы уверены что там один текст на всех кастеров?

Скрин: https://imgur.com/a/UVQStHI
Вот так было когда качал волшебника: https://imgur.com/a/iyKlJGO

**Comment by abalabokhin** [comment]
Да, я уверен, проверьте за барда, например. Но вообще это конечно косяк, что по-разному пишется, привел к одному - выбор заклинаний. Если интересны подробности - в iwd2 есть строчка: "Arcane Spell Selection" и она переводилась как "Выбор заклинания мага" а дальше судя по всему "Уровень X (Level X)" подставлялось автоматически. И почему-то для колдуна в iwd2ee используется именно эта строчка из оригинальных текстов iwd2. Для iwd2ee, они сделали 9 новых строк, типа "Arcane Spell Selection: Level 9", и для волшебника использовались именно они. В общем теперь везде должно быть: "Выбор заклинаний: Уровень X".

**Comment by korn3r** [comment]
Как там все непросто в файлах игры, оказывается. Ну ладно, спасибо.

**Comment by abalabokhin** [comment]
Привет, есть еще какой-то фидбек? Я уже думаю посылать код IWD2EE авторам, и выпускать релиз iwd2_rus...

**Comment by korn3r** [comment]
> Привет, есть еще какой-то фидбек? Я уже думаю посылать код IWD2EE авторам, и выпускать релиз iwd2_rus...

Пока не нашлось (особо и не играл последние пару дней, правда).
Главное что самые бросающиеся в глаза проблемы с гуем поправлены вроде :)

Ну и последние версии мода сейчас можно просто скачать, или надо вас просить подготовить?

**Comment by abalabokhin** [comment]
Да, берите из репозиториев, я сегодня как раз все перекодировал.

**Comment by abalabokhin** [comment]
Закрываю issue за ненадобностью. Еще раз спасибо @korn3r за предоставленный фидбек. Если будут найдены еще неточности - можно будет открывать отдельный issue.
